env:
    - QGIS_VERSION=debian-ltr
    # for now, let's avoid running tests on QGIS3
    # - QGIS_VERSION=debian

dist: trusty
services: docker

language: python

python:
    - "3.5"

before_install:
    - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi
    - if [ "$(git ls-remote --heads https://github.com/gem/oq-engine.git ${BRANCH})" == "" ]; then
        BRANCH='master';
      fi;
    - curl -sfLO https://artifacts.openquake.org/travis/oqdata-${BRANCH}.zip || ( echo "Dump for ${BRANCH} unavailable"; exit 1 )
    - git clone -q -b ${BRANCH} --depth=1 https://github.com/gem/oq-engine.git && echo "Running against oq-engine/${BRANCH}"

install:
    - pip -q install -U pip
    - pip -q install -r oq-engine/requirements-py35-linux64.txt
    - pip -q install -e oq-engine
    - docker build --build-arg uid=$(id -u) -t qgis-builder -f docker/Dockerfile docker/

before_script:
    - oq restore oqdata-${BRANCH}.zip ~/oqdata
    - oq webui start --skip-browser 0.0.0.0:8800 &> webui.log &

script:
    - docker run -e OQ_ENGINE_HOST='http://172.17.0.1:8800' --rm -v $TRAVIS_BUILD_DIR:/io qgis-builder test

after_success:
    - docker run --rm -v $TRAVIS_BUILD_DIR:/io qgis-builder build_apidoc
    - docker run --rm -v $TRAVIS_BUILD_DIR:/io qgis-builder build_manual_html

after_script:
    - cat $TRAVIS_BUILD_DIR/webui.log
