# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_transformation.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

class Ui_TransformationDialog(object):
    def setupUi(self, TransformationDialog):
        TransformationDialog.setObjectName("TransformationDialog")
        TransformationDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TransformationDialog.resize(472, 391)
        TransformationDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(TransformationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.calc_btn = QtWidgets.QPushButton(TransformationDialog)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout.addWidget(self.calc_btn, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.fields_multiselect = ListMultiSelectWidget(TransformationDialog)
        self.fields_multiselect.setObjectName("fields_multiselect")
        self.verticalLayout.addWidget(self.fields_multiselect)
        self.groupBox = QtWidgets.QGroupBox(TransformationDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.overwrite_ckb = QtWidgets.QCheckBox(self.groupBox)
        self.overwrite_ckb.setChecked(False)
        self.overwrite_ckb.setObjectName("overwrite_ckb")
        self.verticalLayout_2.addWidget(self.overwrite_ckb)
        self.warning_lbl = QtWidgets.QLabel(self.groupBox)
        self.warning_lbl.setMinimumSize(QtCore.QSize(0, 35))
        self.warning_lbl.setWordWrap(True)
        self.warning_lbl.setObjectName("warning_lbl")
        self.verticalLayout_2.addWidget(self.warning_lbl)
        self.fieldname_layout = QtWidgets.QHBoxLayout()
        self.fieldname_layout.setObjectName("fieldname_layout")
        self.new_field_name_lbl = QtWidgets.QLabel(self.groupBox)
        self.new_field_name_lbl.setObjectName("new_field_name_lbl")
        self.fieldname_layout.addWidget(self.new_field_name_lbl)
        self.new_field_name_txt = QtWidgets.QLineEdit(self.groupBox)
        self.new_field_name_txt.setEnabled(True)
        self.new_field_name_txt.setMaxLength(10)
        self.new_field_name_txt.setPlaceholderText("")
        self.new_field_name_txt.setObjectName("new_field_name_txt")
        self.fieldname_layout.addWidget(self.new_field_name_txt)
        self.verticalLayout_2.addLayout(self.fieldname_layout)
        self.track_new_field_ckb = QtWidgets.QCheckBox(self.groupBox)
        self.track_new_field_ckb.setEnabled(True)
        self.track_new_field_ckb.setChecked(True)
        self.track_new_field_ckb.setObjectName("track_new_field_ckb")
        self.verticalLayout_2.addWidget(self.track_new_field_ckb)
        self.verticalLayout.addWidget(self.groupBox)
        self.formGroupBox = QtWidgets.QGroupBox(TransformationDialog)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.algorithm_lbl = QtWidgets.QLabel(self.formGroupBox)
        self.algorithm_lbl.setObjectName("algorithm_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.algorithm_lbl)
        self.algorithm_cbx = QtWidgets.QComboBox(self.formGroupBox)
        self.algorithm_cbx.setObjectName("algorithm_cbx")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.algorithm_cbx)
        self.variant_lbl = QtWidgets.QLabel(self.formGroupBox)
        self.variant_lbl.setObjectName("variant_lbl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.variant_lbl)
        self.variant_cbx = QtWidgets.QComboBox(self.formGroupBox)
        self.variant_cbx.setObjectName("variant_cbx")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.variant_cbx)
        self.inverse_ckb = QtWidgets.QCheckBox(self.formGroupBox)
        self.inverse_ckb.setObjectName("inverse_ckb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inverse_ckb)
        self.verticalLayout.addWidget(self.formGroupBox)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(TransformationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)

        self.retranslateUi(TransformationDialog)
        self.buttonBox.accepted.connect(TransformationDialog.accept)
        self.buttonBox.rejected.connect(TransformationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TransformationDialog)

    def retranslateUi(self, TransformationDialog):
        _translate = QtCore.QCoreApplication.translate
        TransformationDialog.setWindowTitle(_translate("TransformationDialog", "Field transformation"))
        self.calc_btn.setText(_translate("TransformationDialog", "Advanced Calculator"))
        self.fields_multiselect.setTitle(_translate("TransformationDialog", "Select fields to transform"))
        self.groupBox.setTitle(_translate("TransformationDialog", "New field(s)"))
        self.overwrite_ckb.setText(_translate("TransformationDialog", "Overwrite the field(s)"))
        self.warning_lbl.setText(_translate("TransformationDialog", "WarningLabel"))
        self.new_field_name_lbl.setText(_translate("TransformationDialog", "Name"))
        self.track_new_field_ckb.setText(_translate("TransformationDialog", "Let all project definitions utilize transformed values"))
        self.formGroupBox.setTitle(_translate("TransformationDialog", "Transformation"))
        self.algorithm_lbl.setText(_translate("TransformationDialog", "Function"))
        self.variant_lbl.setText(_translate("TransformationDialog", "Variant"))
        self.inverse_ckb.setText(_translate("TransformationDialog", "Inverse"))

from list_multiselect_widget import ListMultiSelectWidget
