# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_upload_settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

class Ui_UploadSettingsDialog(object):
    def setupUi(self, UploadSettingsDialog):
        UploadSettingsDialog.setObjectName("UploadSettingsDialog")
        UploadSettingsDialog.resize(509, 369)
        self.verticalLayout = QtWidgets.QVBoxLayout(UploadSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.situation_lbl = QtWidgets.QLabel(UploadSettingsDialog)
        self.situation_lbl.setObjectName("situation_lbl")
        self.verticalLayout.addWidget(self.situation_lbl)
        self.question_lbl = QtWidgets.QLabel(UploadSettingsDialog)
        self.question_lbl.setObjectName("question_lbl")
        self.verticalLayout.addWidget(self.question_lbl)
        self.new_layer_radio = QtWidgets.QRadioButton(UploadSettingsDialog)
        self.new_layer_radio.setChecked(True)
        self.new_layer_radio.setObjectName("new_layer_radio")
        self.upload_action = QtWidgets.QButtonGroup(UploadSettingsDialog)
        self.upload_action.setObjectName("upload_action")
        self.upload_action.addButton(self.new_layer_radio)
        self.verticalLayout.addWidget(self.new_layer_radio)
        self.update_radio = QtWidgets.QRadioButton(UploadSettingsDialog)
        self.update_radio.setObjectName("update_radio")
        self.upload_action.addButton(self.update_radio)
        self.verticalLayout.addWidget(self.update_radio)
        self.explaination_lbl = QtWidgets.QLabel(UploadSettingsDialog)
        self.explaination_lbl.setText("")
        self.explaination_lbl.setObjectName("explaination_lbl")
        self.verticalLayout.addWidget(self.explaination_lbl)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.title_lbl = QtWidgets.QLabel(UploadSettingsDialog)
        self.title_lbl.setObjectName("title_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.title_lbl)
        self.title_le = QtWidgets.QLineEdit(UploadSettingsDialog)
        self.title_le.setObjectName("title_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title_le)
        self.description_lbl = QtWidgets.QLabel(UploadSettingsDialog)
        self.description_lbl.setObjectName("description_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.description_lbl)
        self.description_te = QtWidgets.QTextEdit(UploadSettingsDialog)
        self.description_te.setObjectName("description_te")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.description_te)
        self.zone_label_field_cbx = QtWidgets.QComboBox(UploadSettingsDialog)
        self.zone_label_field_cbx.setObjectName("zone_label_field_cbx")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zone_label_field_cbx)
        self.label = QtWidgets.QLabel(UploadSettingsDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(UploadSettingsDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.license_cbx = QtWidgets.QComboBox(UploadSettingsDialog)
        self.license_cbx.setObjectName("license_cbx")
        self.gridLayout.addWidget(self.license_cbx, 0, 1, 1, 1)
        self.license_info_btn = QtWidgets.QToolButton(UploadSettingsDialog)
        self.license_info_btn.setObjectName("license_info_btn")
        self.gridLayout.addWidget(self.license_info_btn, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.confirm_chk = QtWidgets.QCheckBox(UploadSettingsDialog)
        self.confirm_chk.setObjectName("confirm_chk")
        self.verticalLayout.addWidget(self.confirm_chk)
        self.buttonBox = QtWidgets.QDialogButtonBox(UploadSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(UploadSettingsDialog)
        self.buttonBox.accepted.connect(UploadSettingsDialog.accept)
        self.buttonBox.rejected.connect(UploadSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(UploadSettingsDialog)

    def retranslateUi(self, UploadSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        UploadSettingsDialog.setWindowTitle(_translate("UploadSettingsDialog", "Upload"))
        self.situation_lbl.setText(_translate("UploadSettingsDialog", "It looks like this layer was downloaded from the OpenQuake Platform\n"
"or an older version was previously uploaded there.\n"
"You can create a new layer or just upload the current project definition."))
        self.question_lbl.setText(_translate("UploadSettingsDialog", "What would you like to do?"))
        self.new_layer_radio.setText(_translate("UploadSettingsDialog", "Create a new layer on the platform"))
        self.update_radio.setText(_translate("UploadSettingsDialog", "Update the existing layer on the platform"))
        self.title_lbl.setText(_translate("UploadSettingsDialog", "Title"))
        self.description_lbl.setText(_translate("UploadSettingsDialog", "Description"))
        self.label.setText(_translate("UploadSettingsDialog", "Zone labels field"))
        self.label_6.setText(_translate("UploadSettingsDialog", "License"))
        self.license_info_btn.setText(_translate("UploadSettingsDialog", "Info"))
        self.confirm_chk.setText(_translate("UploadSettingsDialog", "I confirm I have read the license conditions"))

