# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_input_tool_window.ui'
#
# Created: Wed Aug  7 15:48:38 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InputToolWindow(object):
    def setupUi(self, InputToolWindow):
        InputToolWindow.setObjectName(_fromUtf8("InputToolWindow"))
        InputToolWindow.resize(964, 816)
        self.centralwidget = QtGui.QWidget(InputToolWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabwidget = QtGui.QTabWidget(self.centralwidget)
        self.tabwidget.setGeometry(QtCore.QRect(0, 0, 951, 751))
        self.tabwidget.setObjectName(_fromUtf8("tabwidget"))
        self.exposure = QtGui.QWidget()
        self.exposure.setObjectName(_fromUtf8("exposure"))
        self.tabwidget.addTab(self.exposure, _fromUtf8(""))
        self.vulnerability = QtGui.QWidget()
        self.vulnerability.setMinimumSize(QtCore.QSize(947, 718))
        self.vulnerability.setObjectName(_fromUtf8("vulnerability"))
        self.verticalLayoutWidget = QtGui.QWidget(self.vulnerability)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 785, 596))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.addSetBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.addSetBtn.setObjectName(_fromUtf8("addSetBtn"))
        self.verticalLayout_4.addWidget(self.addSetBtn)
        self.addFnBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.addFnBtn.setObjectName(_fromUtf8("addFnBtn"))
        self.verticalLayout_4.addWidget(self.addFnBtn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.removeSetBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.removeSetBtn.setObjectName(_fromUtf8("removeSetBtn"))
        self.verticalLayout_4.addWidget(self.removeSetBtn)
        self.removeFnBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.removeFnBtn.setObjectName(_fromUtf8("removeFnBtn"))
        self.verticalLayout_4.addWidget(self.removeFnBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.vSetsTbl = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.vSetsTbl.setMinimumSize(QtCore.QSize(672, 0))
        self.vSetsTbl.setObjectName(_fromUtf8("vSetsTbl"))
        self.vSetsTbl.setColumnCount(4)
        self.vSetsTbl.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.vSetsTbl.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.vSetsTbl.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.vSetsTbl.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.vSetsTbl.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.vSetsTbl)
        self.ImtTbl = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.ImtTbl.setObjectName(_fromUtf8("ImtTbl"))
        self.ImtTbl.setColumnCount(0)
        self.ImtTbl.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.ImtTbl.setVerticalHeaderItem(0, item)
        self.verticalLayout_5.addWidget(self.ImtTbl)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.vFnTbl = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.vFnTbl.setObjectName(_fromUtf8("vFnTbl"))
        self.vFnTbl.setColumnCount(3)
        self.vFnTbl.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.vFnTbl.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.vFnTbl.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.vFnTbl.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_5.addWidget(self.vFnTbl)
        self.tableWidget = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabwidget.addTab(self.vulnerability, _fromUtf8(""))
        self.fragility = QtGui.QWidget()
        self.fragility.setObjectName(_fromUtf8("fragility"))
        self.tabwidget.addTab(self.fragility, _fromUtf8(""))
        self.sitemodel = QtGui.QWidget()
        self.sitemodel.setObjectName(_fromUtf8("sitemodel"))
        self.tabwidget.addTab(self.sitemodel, _fromUtf8(""))
        self.rupturemodel = QtGui.QWidget()
        self.rupturemodel.setObjectName(_fromUtf8("rupturemodel"))
        self.tabwidget.addTab(self.rupturemodel, _fromUtf8(""))
        self.config = QtGui.QWidget()
        self.config.setObjectName(_fromUtf8("config"))
        self.tabwidget.addTab(self.config, _fromUtf8(""))
        InputToolWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(InputToolWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        InputToolWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(InputToolWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        InputToolWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(InputToolWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        InputToolWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(InputToolWindow)
        self.tabwidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(InputToolWindow)

    def retranslateUi(self, InputToolWindow):
        InputToolWindow.setWindowTitle(QtGui.QApplication.translate("InputToolWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.exposure), QtGui.QApplication.translate("InputToolWindow", "Exposure Model", None, QtGui.QApplication.UnicodeUTF8))
        self.addSetBtn.setText(QtGui.QApplication.translate("InputToolWindow", "Add Set", None, QtGui.QApplication.UnicodeUTF8))
        self.addFnBtn.setText(QtGui.QApplication.translate("InputToolWindow", "Add Fn", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSetBtn.setText(QtGui.QApplication.translate("InputToolWindow", "Remove Set", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFnBtn.setText(QtGui.QApplication.translate("InputToolWindow", "Remove Fn", None, QtGui.QApplication.UnicodeUTF8))
        item = self.vSetsTbl.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Set ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.vSetsTbl.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Asset Category", None, QtGui.QApplication.UnicodeUTF8))
        item = self.vSetsTbl.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Loss Category", None, QtGui.QApplication.UnicodeUTF8))
        item = self.vSetsTbl.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "IMT", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ImtTbl.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "IMT", None, QtGui.QApplication.UnicodeUTF8))
        self.vFnTbl.setSortingEnabled(True)
        item = self.vFnTbl.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Fn ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.vFnTbl.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Prob Dist", None, QtGui.QApplication.UnicodeUTF8))
        item = self.vFnTbl.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "IML", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Loss Ratio", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("InputToolWindow", "Coeff Variation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.vulnerability), QtGui.QApplication.translate("InputToolWindow", "Vulnerability Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.fragility), QtGui.QApplication.translate("InputToolWindow", "Fragility Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.sitemodel), QtGui.QApplication.translate("InputToolWindow", "Site Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.rupturemodel), QtGui.QApplication.translate("InputToolWindow", "Rupture Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.config), QtGui.QApplication.translate("InputToolWindow", "Config File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("InputToolWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

