# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hmtk_ui/hmtkwindow.ui'
#
# Created: Fri Aug 23 15:34:04 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HMTKWindow(object):
    def setupUi(self, HMTKWindow):
        HMTKWindow.setObjectName(_fromUtf8("HMTKWindow"))
        HMTKWindow.resize(1220, 756)
        self.centralWidget = QtGui.QWidget(HMTKWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.stackedFormWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedFormWidget.setObjectName(_fromUtf8("stackedFormWidget"))
        self.stackedWidgetDeclustering = QtGui.QWidget()
        self.stackedWidgetDeclustering.setObjectName(_fromUtf8("stackedWidgetDeclustering"))
        self.gridLayout_2 = QtGui.QGridLayout(self.stackedWidgetDeclustering)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.declusteringGroupBox = QtGui.QGroupBox(self.stackedWidgetDeclustering)
        self.declusteringGroupBox.setObjectName(_fromUtf8("declusteringGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.declusteringGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.declusteringForm = QtGui.QFormLayout()
        self.declusteringForm.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.declusteringForm.setObjectName(_fromUtf8("declusteringForm"))
        self.declusteringTimeWindowFunctionLabel = QtGui.QLabel(self.declusteringGroupBox)
        self.declusteringTimeWindowFunctionLabel.setObjectName(_fromUtf8("declusteringTimeWindowFunctionLabel"))
        self.declusteringForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.declusteringTimeWindowFunctionLabel)
        self.declusteringTimeWindowFunctionCombo = QtGui.QComboBox(self.declusteringGroupBox)
        self.declusteringTimeWindowFunctionCombo.setObjectName(_fromUtf8("declusteringTimeWindowFunctionCombo"))
        self.declusteringTimeWindowFunctionCombo.addItem(_fromUtf8(""))
        self.declusteringTimeWindowFunctionCombo.setItemText(0, _fromUtf8(""))
        self.declusteringTimeWindowFunctionCombo.addItem(_fromUtf8(""))
        self.declusteringTimeWindowFunctionCombo.addItem(_fromUtf8(""))
        self.declusteringForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.declusteringTimeWindowFunctionCombo)
        self.declusteringTimeWindowLabel = QtGui.QLabel(self.declusteringGroupBox)
        self.declusteringTimeWindowLabel.setObjectName(_fromUtf8("declusteringTimeWindowLabel"))
        self.declusteringForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.declusteringTimeWindowLabel)
        self.declusteringTimeWindowInput = QtGui.QLineEdit(self.declusteringGroupBox)
        self.declusteringTimeWindowInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.declusteringTimeWindowInput.setObjectName(_fromUtf8("declusteringTimeWindowInput"))
        self.declusteringForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.declusteringTimeWindowInput)
        self.declusteringMethodLabel = QtGui.QLabel(self.declusteringGroupBox)
        self.declusteringMethodLabel.setObjectName(_fromUtf8("declusteringMethodLabel"))
        self.declusteringForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.declusteringMethodLabel)
        self.declusteringMethodComboBox = QtGui.QComboBox(self.declusteringGroupBox)
        self.declusteringMethodComboBox.setObjectName(_fromUtf8("declusteringMethodComboBox"))
        self.declusteringMethodComboBox.addItem(_fromUtf8(""))
        self.declusteringMethodComboBox.setItemText(0, _fromUtf8(""))
        self.declusteringMethodComboBox.addItem(_fromUtf8(""))
        self.declusteringMethodComboBox.addItem(_fromUtf8(""))
        self.declusteringForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.declusteringMethodComboBox)
        self.verticalLayout_2.addLayout(self.declusteringForm)
        self.declusteringButtons = QtGui.QHBoxLayout()
        self.declusteringButtons.setObjectName(_fromUtf8("declusteringButtons"))
        self.declusterButton = QtGui.QPushButton(self.declusteringGroupBox)
        self.declusterButton.setObjectName(_fromUtf8("declusterButton"))
        self.declusteringButtons.addWidget(self.declusterButton)
        self.declusteringPurgeButton = QtGui.QPushButton(self.declusteringGroupBox)
        self.declusteringPurgeButton.setObjectName(_fromUtf8("declusteringPurgeButton"))
        self.declusteringButtons.addWidget(self.declusteringPurgeButton)
        self.verticalLayout_2.addLayout(self.declusteringButtons)
        self.declusteringChart = FigureCanvasQTAggWidget(self.declusteringGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.declusteringChart.sizePolicy().hasHeightForWidth())
        self.declusteringChart.setSizePolicy(sizePolicy)
        self.declusteringChart.setMinimumSize(QtCore.QSize(0, 300))
        self.declusteringChart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.declusteringChart.setObjectName(_fromUtf8("declusteringChart"))
        self.verticalLayout_2.addWidget(self.declusteringChart)
        self.gridLayout_2.addWidget(self.declusteringGroupBox, 0, 0, 1, 1)
        self.stackedFormWidget.addWidget(self.stackedWidgetDeclustering)
        self.stackedWidgetCompleteness = QtGui.QWidget()
        self.stackedWidgetCompleteness.setObjectName(_fromUtf8("stackedWidgetCompleteness"))
        self.gridLayout_3 = QtGui.QGridLayout(self.stackedWidgetCompleteness)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.completenessGroupBox = QtGui.QGroupBox(self.stackedWidgetCompleteness)
        self.completenessGroupBox.setObjectName(_fromUtf8("completenessGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.completenessGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.completenessForm = QtGui.QFormLayout()
        self.completenessForm.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.completenessForm.setObjectName(_fromUtf8("completenessForm"))
        self.completenessMagnitudeBinLabel = QtGui.QLabel(self.completenessGroupBox)
        self.completenessMagnitudeBinLabel.setObjectName(_fromUtf8("completenessMagnitudeBinLabel"))
        self.completenessForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.completenessMagnitudeBinLabel)
        self.completenessMagnitudeBinInput = QtGui.QLineEdit(self.completenessGroupBox)
        self.completenessMagnitudeBinInput.setObjectName(_fromUtf8("completenessMagnitudeBinInput"))
        self.completenessForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.completenessMagnitudeBinInput)
        self.completenessTimeBinLabel = QtGui.QLabel(self.completenessGroupBox)
        self.completenessTimeBinLabel.setObjectName(_fromUtf8("completenessTimeBinLabel"))
        self.completenessForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.completenessTimeBinLabel)
        self.completenessTimeBinInput = QtGui.QLineEdit(self.completenessGroupBox)
        self.completenessTimeBinInput.setObjectName(_fromUtf8("completenessTimeBinInput"))
        self.completenessForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.completenessTimeBinInput)
        self.completenessIncrementLockLabel = QtGui.QLabel(self.completenessGroupBox)
        self.completenessIncrementLockLabel.setObjectName(_fromUtf8("completenessIncrementLockLabel"))
        self.completenessForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.completenessIncrementLockLabel)
        self.completenessIncrementLockInput = QtGui.QComboBox(self.completenessGroupBox)
        self.completenessIncrementLockInput.setObjectName(_fromUtf8("completenessIncrementLockInput"))
        self.completenessIncrementLockInput.addItem(_fromUtf8(""))
        self.completenessIncrementLockInput.setItemText(0, _fromUtf8(""))
        self.completenessIncrementLockInput.addItem(_fromUtf8(""))
        self.completenessIncrementLockInput.addItem(_fromUtf8(""))
        self.completenessForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.completenessIncrementLockInput)
        self.verticalLayout_3.addLayout(self.completenessForm)
        self.completenessButtons = QtGui.QHBoxLayout()
        self.completenessButtons.setObjectName(_fromUtf8("completenessButtons"))
        self.completenessButton = QtGui.QPushButton(self.completenessGroupBox)
        self.completenessButton.setObjectName(_fromUtf8("completenessButton"))
        self.completenessButtons.addWidget(self.completenessButton)
        self.completenessPurgeButton = QtGui.QPushButton(self.completenessGroupBox)
        self.completenessPurgeButton.setObjectName(_fromUtf8("completenessPurgeButton"))
        self.completenessButtons.addWidget(self.completenessPurgeButton)
        self.verticalLayout_3.addLayout(self.completenessButtons)
        self.completenessChart = FigureCanvasQTAggWidget(self.completenessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completenessChart.sizePolicy().hasHeightForWidth())
        self.completenessChart.setSizePolicy(sizePolicy)
        self.completenessChart.setMinimumSize(QtCore.QSize(0, 300))
        self.completenessChart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.completenessChart.setObjectName(_fromUtf8("completenessChart"))
        self.verticalLayout_3.addWidget(self.completenessChart)
        self.gridLayout_3.addWidget(self.completenessGroupBox, 0, 0, 1, 1)
        self.stackedFormWidget.addWidget(self.stackedWidgetCompleteness)
        self.stackedWidgetRecurrenceModel = QtGui.QWidget()
        self.stackedWidgetRecurrenceModel.setObjectName(_fromUtf8("stackedWidgetRecurrenceModel"))
        self.gridLayout_4 = QtGui.QGridLayout(self.stackedWidgetRecurrenceModel)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.recurrenceModelGroupBox = QtGui.QGroupBox(self.stackedWidgetRecurrenceModel)
        self.recurrenceModelGroupBox.setObjectName(_fromUtf8("recurrenceModelGroupBox"))
        self.layoutWidget_3 = QtGui.QWidget(self.recurrenceModelGroupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 50, 328, 250))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.recurrenceModelForm = QtGui.QFormLayout(self.layoutWidget_3)
        self.recurrenceModelForm.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.recurrenceModelForm.setMargin(0)
        self.recurrenceModelForm.setObjectName(_fromUtf8("recurrenceModelForm"))
        self.recurrenceModelMethodLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelMethodLabel.setObjectName(_fromUtf8("recurrenceModelMethodLabel"))
        self.recurrenceModelForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.recurrenceModelMethodLabel)
        self.recurrenceModelMethodInput = QtGui.QComboBox(self.layoutWidget_3)
        self.recurrenceModelMethodInput.setObjectName(_fromUtf8("recurrenceModelMethodInput"))
        self.recurrenceModelMethodInput.addItem(_fromUtf8(""))
        self.recurrenceModelMethodInput.addItem(_fromUtf8(""))
        self.recurrenceModelMethodInput.addItem(_fromUtf8(""))
        self.recurrenceModelForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.recurrenceModelMethodInput)
        self.recurrenceModelMagnitudeIntervalLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelMagnitudeIntervalLabel.setObjectName(_fromUtf8("recurrenceModelMagnitudeIntervalLabel"))
        self.recurrenceModelForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.recurrenceModelMagnitudeIntervalLabel)
        self.recurrenceModelMagnitudeIntervalInput = QtGui.QLineEdit(self.layoutWidget_3)
        self.recurrenceModelMagnitudeIntervalInput.setObjectName(_fromUtf8("recurrenceModelMagnitudeIntervalInput"))
        self.recurrenceModelForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.recurrenceModelMagnitudeIntervalInput)
        self.recurrenceModelAverageTypeLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelAverageTypeLabel.setObjectName(_fromUtf8("recurrenceModelAverageTypeLabel"))
        self.recurrenceModelForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.recurrenceModelAverageTypeLabel)
        self.recurrenceModelAverageTypeInput = QtGui.QComboBox(self.layoutWidget_3)
        self.recurrenceModelAverageTypeInput.setObjectName(_fromUtf8("recurrenceModelAverageTypeInput"))
        self.recurrenceModelAverageTypeInput.addItem(_fromUtf8(""))
        self.recurrenceModelAverageTypeInput.addItem(_fromUtf8(""))
        self.recurrenceModelForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.recurrenceModelAverageTypeInput)
        self.recurrenceModelReferenceMagnitudeLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelReferenceMagnitudeLabel.setObjectName(_fromUtf8("recurrenceModelReferenceMagnitudeLabel"))
        self.recurrenceModelForm.setWidget(3, QtGui.QFormLayout.LabelRole, self.recurrenceModelReferenceMagnitudeLabel)
        self.recurrenceModelReferenceMagnitudeInput = QtGui.QLineEdit(self.layoutWidget_3)
        self.recurrenceModelReferenceMagnitudeInput.setObjectName(_fromUtf8("recurrenceModelReferenceMagnitudeInput"))
        self.recurrenceModelForm.setWidget(3, QtGui.QFormLayout.FieldRole, self.recurrenceModelReferenceMagnitudeInput)
        self.recurrenceModelBValueInputLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelBValueInputLabel.setObjectName(_fromUtf8("recurrenceModelBValueInputLabel"))
        self.recurrenceModelForm.setWidget(4, QtGui.QFormLayout.LabelRole, self.recurrenceModelBValueInputLabel)
        self.recurrenceModelBValueInput = QtGui.QLineEdit(self.layoutWidget_3)
        self.recurrenceModelBValueInput.setObjectName(_fromUtf8("recurrenceModelBValueInput"))
        self.recurrenceModelForm.setWidget(4, QtGui.QFormLayout.FieldRole, self.recurrenceModelBValueInput)
        self.recurrenceModelToleranceLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelToleranceLabel.setObjectName(_fromUtf8("recurrenceModelToleranceLabel"))
        self.recurrenceModelForm.setWidget(5, QtGui.QFormLayout.LabelRole, self.recurrenceModelToleranceLabel)
        self.recurrenceModelToleranceInput = QtGui.QLineEdit(self.layoutWidget_3)
        self.recurrenceModelToleranceInput.setObjectName(_fromUtf8("recurrenceModelToleranceInput"))
        self.recurrenceModelForm.setWidget(5, QtGui.QFormLayout.FieldRole, self.recurrenceModelToleranceInput)
        self.recurrenceModelMaxIterationLabel = QtGui.QLabel(self.layoutWidget_3)
        self.recurrenceModelMaxIterationLabel.setObjectName(_fromUtf8("recurrenceModelMaxIterationLabel"))
        self.recurrenceModelForm.setWidget(6, QtGui.QFormLayout.LabelRole, self.recurrenceModelMaxIterationLabel)
        self.recurrenceModelMaxIterationInput = QtGui.QLineEdit(self.layoutWidget_3)
        self.recurrenceModelMaxIterationInput.setObjectName(_fromUtf8("recurrenceModelMaxIterationInput"))
        self.recurrenceModelForm.setWidget(6, QtGui.QFormLayout.FieldRole, self.recurrenceModelMaxIterationInput)
        self.gridLayout_4.addWidget(self.recurrenceModelGroupBox, 0, 0, 1, 1)
        self.stackedFormWidget.addWidget(self.stackedWidgetRecurrenceModel)
        self.stackedWidgetMaxMagnitude = QtGui.QWidget()
        self.stackedWidgetMaxMagnitude.setObjectName(_fromUtf8("stackedWidgetMaxMagnitude"))
        self.gridLayout_5 = QtGui.QGridLayout(self.stackedWidgetMaxMagnitude)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.maxMagnitudeGroupBox = QtGui.QGroupBox(self.stackedWidgetMaxMagnitude)
        self.maxMagnitudeGroupBox.setObjectName(_fromUtf8("maxMagnitudeGroupBox"))
        self.layoutWidget_4 = QtGui.QWidget(self.maxMagnitudeGroupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 40, 352, 214))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.maxMagnitudeForm = QtGui.QFormLayout(self.layoutWidget_4)
        self.maxMagnitudeForm.setMargin(0)
        self.maxMagnitudeForm.setObjectName(_fromUtf8("maxMagnitudeForm"))
        self.maxMagnitudeLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeLabel.setObjectName(_fromUtf8("maxMagnitudeLabel"))
        self.maxMagnitudeForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.maxMagnitudeLabel)
        self.maxMagnitudeInput = QtGui.QLineEdit(self.layoutWidget_4)
        self.maxMagnitudeInput.setObjectName(_fromUtf8("maxMagnitudeInput"))
        self.maxMagnitudeForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.maxMagnitudeInput)
        self.maxMagnitudeUncertaintyLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeUncertaintyLabel.setObjectName(_fromUtf8("maxMagnitudeUncertaintyLabel"))
        self.maxMagnitudeForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.maxMagnitudeUncertaintyLabel)
        self.maxMagnitudeUncertaintyInput = QtGui.QLineEdit(self.layoutWidget_4)
        self.maxMagnitudeUncertaintyInput.setObjectName(_fromUtf8("maxMagnitudeUncertaintyInput"))
        self.maxMagnitudeForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.maxMagnitudeUncertaintyInput)
        self.maxMagnitudeBValueLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeBValueLabel.setObjectName(_fromUtf8("maxMagnitudeBValueLabel"))
        self.maxMagnitudeForm.setWidget(3, QtGui.QFormLayout.LabelRole, self.maxMagnitudeBValueLabel)
        self.maxMagnitudeBValueInput = QtGui.QLineEdit(self.layoutWidget_4)
        self.maxMagnitudeBValueInput.setObjectName(_fromUtf8("maxMagnitudeBValueInput"))
        self.maxMagnitudeForm.setWidget(3, QtGui.QFormLayout.FieldRole, self.maxMagnitudeBValueInput)
        self.maxMagnitudeMinimumMagnitudeLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeMinimumMagnitudeLabel.setObjectName(_fromUtf8("maxMagnitudeMinimumMagnitudeLabel"))
        self.maxMagnitudeForm.setWidget(4, QtGui.QFormLayout.LabelRole, self.maxMagnitudeMinimumMagnitudeLabel)
        self.maxMagnitudeMinimumMagnitudeInput = QtGui.QLineEdit(self.layoutWidget_4)
        self.maxMagnitudeMinimumMagnitudeInput.setObjectName(_fromUtf8("maxMagnitudeMinimumMagnitudeInput"))
        self.maxMagnitudeForm.setWidget(4, QtGui.QFormLayout.FieldRole, self.maxMagnitudeMinimumMagnitudeInput)
        self.maxMagnitudeToleranceLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeToleranceLabel.setObjectName(_fromUtf8("maxMagnitudeToleranceLabel"))
        self.maxMagnitudeForm.setWidget(5, QtGui.QFormLayout.LabelRole, self.maxMagnitudeToleranceLabel)
        self.maxMagnitudeToleranceLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.maxMagnitudeToleranceLineEdit.setObjectName(_fromUtf8("maxMagnitudeToleranceLineEdit"))
        self.maxMagnitudeForm.setWidget(5, QtGui.QFormLayout.FieldRole, self.maxMagnitudeToleranceLineEdit)
        self.maxMagnitudeMaximumIterationsLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeMaximumIterationsLabel.setObjectName(_fromUtf8("maxMagnitudeMaximumIterationsLabel"))
        self.maxMagnitudeForm.setWidget(6, QtGui.QFormLayout.LabelRole, self.maxMagnitudeMaximumIterationsLabel)
        self.maxMagnitudeMaximumIterationsInput = QtGui.QLineEdit(self.layoutWidget_4)
        self.maxMagnitudeMaximumIterationsInput.setObjectName(_fromUtf8("maxMagnitudeMaximumIterationsInput"))
        self.maxMagnitudeForm.setWidget(6, QtGui.QFormLayout.FieldRole, self.maxMagnitudeMaximumIterationsInput)
        self.maxMagnitudeMethodLabel = QtGui.QLabel(self.layoutWidget_4)
        self.maxMagnitudeMethodLabel.setObjectName(_fromUtf8("maxMagnitudeMethodLabel"))
        self.maxMagnitudeForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.maxMagnitudeMethodLabel)
        self.maxMagnitudeMethodComboBox = QtGui.QComboBox(self.layoutWidget_4)
        self.maxMagnitudeMethodComboBox.setObjectName(_fromUtf8("maxMagnitudeMethodComboBox"))
        self.maxMagnitudeMethodComboBox.addItem(_fromUtf8(""))
        self.maxMagnitudeMethodComboBox.setItemText(0, _fromUtf8(""))
        self.maxMagnitudeMethodComboBox.addItem(_fromUtf8(""))
        self.maxMagnitudeMethodComboBox.addItem(_fromUtf8(""))
        self.maxMagnitudeMethodComboBox.addItem(_fromUtf8(""))
        self.maxMagnitudeForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxMagnitudeMethodComboBox)
        self.gridLayout_5.addWidget(self.maxMagnitudeGroupBox, 0, 0, 1, 1)
        self.stackedFormWidget.addWidget(self.stackedWidgetMaxMagnitude)
        self.stackedWidgetSmoothedSeismicity = QtGui.QWidget()
        self.stackedWidgetSmoothedSeismicity.setObjectName(_fromUtf8("stackedWidgetSmoothedSeismicity"))
        self.gridLayout_6 = QtGui.QGridLayout(self.stackedWidgetSmoothedSeismicity)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.smoothedSeismicityGroupBox = QtGui.QGroupBox(self.stackedWidgetSmoothedSeismicity)
        self.smoothedSeismicityGroupBox.setObjectName(_fromUtf8("smoothedSeismicityGroupBox"))
        self.layoutWidget_5 = QtGui.QWidget(self.smoothedSeismicityGroupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 30, 234, 88))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.smoothedSeismicityFormLayout = QtGui.QFormLayout(self.layoutWidget_5)
        self.smoothedSeismicityFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.smoothedSeismicityFormLayout.setMargin(0)
        self.smoothedSeismicityFormLayout.setObjectName(_fromUtf8("smoothedSeismicityFormLayout"))
        self.smoothedSeismicityGridSpacingLabel = QtGui.QLabel(self.layoutWidget_5)
        self.smoothedSeismicityGridSpacingLabel.setObjectName(_fromUtf8("smoothedSeismicityGridSpacingLabel"))
        self.smoothedSeismicityFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.smoothedSeismicityGridSpacingLabel)
        self.smoothedSeismicityGridSpacingInput = QtGui.QLineEdit(self.layoutWidget_5)
        self.smoothedSeismicityGridSpacingInput.setObjectName(_fromUtf8("smoothedSeismicityGridSpacingInput"))
        self.smoothedSeismicityFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.smoothedSeismicityGridSpacingInput)
        self.smoothedSeismicity3DDistancesLabel = QtGui.QLabel(self.layoutWidget_5)
        self.smoothedSeismicity3DDistancesLabel.setObjectName(_fromUtf8("smoothedSeismicity3DDistancesLabel"))
        self.smoothedSeismicityFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.smoothedSeismicity3DDistancesLabel)
        self.smoothed3DDistancesInput = QtGui.QLineEdit(self.layoutWidget_5)
        self.smoothed3DDistancesInput.setObjectName(_fromUtf8("smoothed3DDistancesInput"))
        self.smoothedSeismicityFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.smoothed3DDistancesInput)
        self.smoothedSeismicityBValueLabel = QtGui.QLabel(self.layoutWidget_5)
        self.smoothedSeismicityBValueLabel.setObjectName(_fromUtf8("smoothedSeismicityBValueLabel"))
        self.smoothedSeismicityFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.smoothedSeismicityBValueLabel)
        self.smoothedSeismicityBValueInput = QtGui.QLineEdit(self.layoutWidget_5)
        self.smoothedSeismicityBValueInput.setObjectName(_fromUtf8("smoothedSeismicityBValueInput"))
        self.smoothedSeismicityFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.smoothedSeismicityBValueInput)
        self.gridLayout_6.addWidget(self.smoothedSeismicityGroupBox, 0, 0, 1, 1)
        self.stackedFormWidget.addWidget(self.stackedWidgetSmoothedSeismicity)
        self.horizontalLayout.addWidget(self.stackedFormWidget)
        self.outputVerticalLayout = QtGui.QVBoxLayout()
        self.outputVerticalLayout.setObjectName(_fromUtf8("outputVerticalLayout"))
        self.mapWidget = QgsMapCanvas(self.centralWidget)
        self.mapWidget.setMinimumSize(QtCore.QSize(300, 300))
        self.mapWidget.setObjectName(_fromUtf8("mapWidget"))
        self.outputVerticalLayout.addWidget(self.mapWidget)
        self.outputTableView = QtGui.QTableView(self.centralWidget)
        self.outputTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.outputTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.outputTableView.setSortingEnabled(True)
        self.outputTableView.setObjectName(_fromUtf8("outputTableView"))
        self.outputTableView.verticalHeader().setVisible(False)
        self.outputVerticalLayout.addWidget(self.outputTableView)
        self.horizontalLayout.addLayout(self.outputVerticalLayout)
        HMTKWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(HMTKWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1220, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        HMTKWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(HMTKWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        HMTKWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_catalogue = QtGui.QAction(HMTKWindow)
        self.actionLoad_catalogue.setObjectName(_fromUtf8("actionLoad_catalogue"))
        self.actionDeclustering = QtGui.QAction(HMTKWindow)
        self.actionDeclustering.setObjectName(_fromUtf8("actionDeclustering"))
        self.actionRecurrenceModel = QtGui.QAction(HMTKWindow)
        self.actionRecurrenceModel.setObjectName(_fromUtf8("actionRecurrenceModel"))
        self.actionCompleteness = QtGui.QAction(HMTKWindow)
        self.actionCompleteness.setObjectName(_fromUtf8("actionCompleteness"))
        self.actionMaximumMagnitude = QtGui.QAction(HMTKWindow)
        self.actionMaximumMagnitude.setObjectName(_fromUtf8("actionMaximumMagnitude"))
        self.actionSmoothedSeismicity = QtGui.QAction(HMTKWindow)
        self.actionSmoothedSeismicity.setObjectName(_fromUtf8("actionSmoothedSeismicity"))
        self.actionSave_catalogue = QtGui.QAction(HMTKWindow)
        self.actionSave_catalogue.setObjectName(_fromUtf8("actionSave_catalogue"))
        self.menuFile.addAction(self.actionLoad_catalogue)
        self.menuFile.addAction(self.actionSave_catalogue)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuTools.addAction(self.actionDeclustering)
        self.menuTools.addAction(self.actionCompleteness)
        self.menuTools.addAction(self.actionRecurrenceModel)
        self.menuTools.addAction(self.actionMaximumMagnitude)
        self.menuTools.addAction(self.actionSmoothedSeismicity)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(HMTKWindow)
        self.stackedFormWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(HMTKWindow)

    def retranslateUi(self, HMTKWindow):
        HMTKWindow.setWindowTitle(QtGui.QApplication.translate("HMTKWindow", "HMTKWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringGroupBox.setTitle(QtGui.QApplication.translate("HMTKWindow", "Declustering", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringTimeWindowFunctionLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Time window function", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringTimeWindowFunctionCombo.setItemText(1, QtGui.QApplication.translate("HMTKWindow", "Uhrhammer", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringTimeWindowFunctionCombo.setItemText(2, QtGui.QApplication.translate("HMTKWindow", "Gardner Knopoff", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringTimeWindowLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Time window", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringMethodLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringMethodComboBox.setItemText(1, QtGui.QApplication.translate("HMTKWindow", "Gardner Knopoff Type 1", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringMethodComboBox.setItemText(2, QtGui.QApplication.translate("HMTKWindow", "Afteran", None, QtGui.QApplication.UnicodeUTF8))
        self.declusterButton.setText(QtGui.QApplication.translate("HMTKWindow", "Decluster", None, QtGui.QApplication.UnicodeUTF8))
        self.declusteringPurgeButton.setText(QtGui.QApplication.translate("HMTKWindow", "Purge Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessGroupBox.setTitle(QtGui.QApplication.translate("HMTKWindow", "Completeness", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessMagnitudeBinLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Magnitude Bin", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessTimeBinLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Time Bin", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessIncrementLockLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Increment Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessIncrementLockInput.setItemText(1, QtGui.QApplication.translate("HMTKWindow", "True", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessIncrementLockInput.setItemText(2, QtGui.QApplication.translate("HMTKWindow", "False", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessButton.setText(QtGui.QApplication.translate("HMTKWindow", "Run Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.completenessPurgeButton.setText(QtGui.QApplication.translate("HMTKWindow", "Purge Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelGroupBox.setTitle(QtGui.QApplication.translate("HMTKWindow", "Recurrence Model", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelMethodLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelMethodInput.setItemText(0, QtGui.QApplication.translate("HMTKWindow", "Maximum Likelihood", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelMethodInput.setItemText(1, QtGui.QApplication.translate("HMTKWindow", "Kijko and Smit", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelMethodInput.setItemText(2, QtGui.QApplication.translate("HMTKWindow", "Weichert", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelMagnitudeIntervalLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Magnitude Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelAverageTypeLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Average Type", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelAverageTypeInput.setItemText(0, QtGui.QApplication.translate("HMTKWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelAverageTypeInput.setItemText(1, QtGui.QApplication.translate("HMTKWindow", "None (Kijko and Smit)", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelReferenceMagnitudeLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Reference Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelBValueInputLabel.setText(QtGui.QApplication.translate("HMTKWindow", "b value (Weichert)", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelToleranceLabel.setText(QtGui.QApplication.translate("HMTKWindow", "tolerance (Weichert)", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceModelMaxIterationLabel.setText(QtGui.QApplication.translate("HMTKWindow", "max iteration", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeGroupBox.setTitle(QtGui.QApplication.translate("HMTKWindow", "Maximum Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Max Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeUncertaintyLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Max Mag. Uncertainty", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeBValueLabel.setText(QtGui.QApplication.translate("HMTKWindow", "b value", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeMinimumMagnitudeLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Min Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeToleranceLabel.setText(QtGui.QApplication.translate("HMTKWindow", "tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeMaximumIterationsLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Max iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeMethodLabel.setText(QtGui.QApplication.translate("HMTKWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeMethodComboBox.setItemText(1, QtGui.QApplication.translate("HMTKWindow", "Kijko Sellevol (Fixed b)", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeMethodComboBox.setItemText(2, QtGui.QApplication.translate("HMTKWindow", "Kijko et al. (Uncertain b)", None, QtGui.QApplication.UnicodeUTF8))
        self.maxMagnitudeMethodComboBox.setItemText(3, QtGui.QApplication.translate("HMTKWindow", "Non Parametric Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothedSeismicityGroupBox.setTitle(QtGui.QApplication.translate("HMTKWindow", "Smoothed Seismicity", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothedSeismicityGridSpacingLabel.setText(QtGui.QApplication.translate("HMTKWindow", "grid spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothedSeismicity3DDistancesLabel.setText(QtGui.QApplication.translate("HMTKWindow", "3d distances", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothedSeismicityBValueLabel.setText(QtGui.QApplication.translate("HMTKWindow", "b value", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("HMTKWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("HMTKWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("HMTKWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("HMTKWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_catalogue.setText(QtGui.QApplication.translate("HMTKWindow", "Load catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_catalogue.setShortcut(QtGui.QApplication.translate("HMTKWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeclustering.setText(QtGui.QApplication.translate("HMTKWindow", "Declustering", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeclustering.setShortcut(QtGui.QApplication.translate("HMTKWindow", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecurrenceModel.setText(QtGui.QApplication.translate("HMTKWindow", "Recurrence Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecurrenceModel.setShortcut(QtGui.QApplication.translate("HMTKWindow", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteness.setText(QtGui.QApplication.translate("HMTKWindow", "Completeness", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleteness.setShortcut(QtGui.QApplication.translate("HMTKWindow", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaximumMagnitude.setText(QtGui.QApplication.translate("HMTKWindow", "Maximum Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaximumMagnitude.setShortcut(QtGui.QApplication.translate("HMTKWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSmoothedSeismicity.setText(QtGui.QApplication.translate("HMTKWindow", "Smoothed Seismicity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSmoothedSeismicity.setShortcut(QtGui.QApplication.translate("HMTKWindow", "Ctrl+5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_catalogue.setText(QtGui.QApplication.translate("HMTKWindow", "Save catalogue", None, QtGui.QApplication.UnicodeUTF8))

from widgets import FigureCanvasQTAggWidget
from qgis.gui import QgsMapCanvas
