name: test python
on:
  push:
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-18.04, ubuntu-20.04]
        #python-version: [3.6, 3.7, 3.8]
        python-version: [3.8]
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      GITHUB_DEF_BR:  ${{ github.event.repository.default_branch }}
      GITHUB_REF:  ${{ github.ref }}
      GITHUB_HD_REF:  ${{ github.head_ref }}
      GITHUB_BS_REF:  ${{ github.base_ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone engine and restore oqdata
        run: |
          echo " Check if this is a pull request or not"
          if [ -z "$GITHUB_HD_REF" ]
             then
              echo " Is not a pull request, use branch: $GITHUB_DEF_BR"
              GITHUB_BR=`echo ${{ github.event.repository.default_branch }}`
             else
              echo " Is a pull request, use branch: $GITHUB_HD_BR"
              GITHUB_BR=`echo ${{ github.head_ref }}`
          fi
          git clone -b $GITHUB_BR --depth=1 https://github.com/gem/oq-engine.git
          PY_VER=`echo py${{ matrix.python-version }} | tr -d .`
          echo $PY_VER
          cd oq-engine
          pip3 install -r requirements-$PY_VER-linux64.txt
          pip3 install -e .
          cd ..
          echo "Dump for $GITHUB_BR branch "
          curl -sfLO https://artifacts.openquake.org/travis/oqdata-${GITHUB_BR}.zip
          mkdir ~/oqdata
          oq restore oqdata-${GITHUB_BR}.zip ~/oqdata
          oq webui start 0.0.0.0:8800 --skip-browser & > webui.log

      - name: Run unit tests
        run: |
            mkdir /tests_directory
            ./scripts/run_unit_tests.sh
      - name: Run integration tests
        run: ./scripts/run_integration_tests.sh
      - name: Make documentation
        run: ./scripts/make_doc.sh
      - name: Display Web UI log
        run: cat webui.log
